### PR TITLE
Provide hook to disable GVM alias

### PR DESCRIPTION
**Pull request by flyinprogrammer**
This would be nice so that I can now actually run both sdkman and [gvm](https://github.com/moovweb/gvm) side by side. :smile: 

Awesome job with the total rebrand btw - this is super duper awesome!

### CODE REVIEW

**Comment by marc0der** [comment]
Thank you! Much appreciated!

Just curious: Why you would want to run them side by side? GVM is no longer supported and will be blown away by the first selfupdate.

Also, that alias is there for a purpose: many users feeling nostalgic have asked for the `gvm` command to still work as it did before. It also provides backward compatibility for automated environments like CI.

**Comment by marc0der** [comment]
EDIT: I just saw that you were referring to gvm, the Go Version Manager. In that case we could probably make it configurable instead.

**Comment by flyinprogrammer** [comment]
How about this? 
I force-pushed over the previous commit, now there is an environment variable hook.

**Comment by marc0der** [comment]
Hi Alan, thanks for the great work so far; it's already starting to look a lot better. Currently all configuration happens using config that lives under `~/.sdkman/etc/config`. Please see the [configuration](http://sdkman.io/usage.html#config) section on our site for other such config.

I would expect it to be read from there, with the configuration set to `false` by default. A good name would be something like `sdkman_disable_gvm_alias`.

Hope it's making sense so far!

**Comment by flyinprogrammer** [comment]
Cool stuff - this work? (seems to work locally) I chose to explicitly check for `sdkman_disable_gvm_alias ` to be `true` so that even should `sdkman_disable_gvm_alias` be unset the gvm alias will be used.

I wanted to go write some cucumber tests but when I run `./gradlew test` I get: 

```
1120 tests completed, 284 failed, 693 skipped
:test FAILED
```

Should that many be failing?

**Comment by marc0der** [comment]
Sounds good to me. The cucumber tests are all working, but the build is
simply run with a ./gradlew.

**Comment by marc0der** [comment]
I've gone ahead and implemented this, will roll it out shortly.

**Comment by flyinprogrammer** [comment]
oh ok - i'm sorry i never got you tests - i just got busy with other stuff which is a super lame excuse :-1:

**Comment by marc0der** [comment]
Don't worry about that, it ended up being trivial to change. Thanks for
your contribution anyway, it's much appreciated.

**Comment by deas** [comment]
The alias is set when we set disable to "true"?

Found that slightly unexpected. ;)

```
if [[ "$sdkman_disable_gvm_alias" == "true" ]]; then                                                                                                             
        alias gvm="sdk"                                                                                                                                          
fi
```

**Comment by marc0der** [comment]
Yes, we can fix that ;-)

**Comment by marc0der** [comment]
Fixed, I'll roll it out later today. Serves us right for not starting with a test :-P

**Pull request closed without merging**
