### PR TITLE
Prevent Re-initialization of zsh completion system

### PR DESCRIPTION
**Pull request by andrewrembrandt**
* Resolves issue #947 with gcloud sdk completions not working

### CODE REVIEW

**Review by marc0der — APPROVED** [review]
LGTM!

**Comment by marc0der** [comment]
I'll wait until GitHub actions are back up before merging. Thanks for contributing!

**Comment by marc0der** [comment]
@andrewrembrandt This is now deployed to our beta channel. If you can confirm that it solves your problem, I'll promote it to the prod environment.

**Comment by andrewrembrandt** [comment]
> @andrewrembrandt This is now deployed to our beta channel. If you can confirm that it solves your problem, I'll promote it to the prod environment.

@marc0der Just reproduced the original bug, and confirmed it's fixed with the latest beta :+1: 
(Great to see a Kotlin FP book by the way!)

**Comment by rbbl-dev** [comment]
is there a estimate on when the next stable release with this fix will be published?

**Comment by marc0der** [comment]
My bad, I forgot to release that. I'll do that today.

**Comment by marc0der** [comment]
This is now released as 5.12.3 :tada:

**Pull request merged**
