### PR TITLE
Add completion for sdk install

### PR DESCRIPTION
**Pull request by helpermethod**
This PR adds Bash completion for `sdk install`.

### CODE REVIEW

**Comment by helpermethod** [comment]
I've found some pointers for testing this, so I will add some tests for the most critical completions (`env`, `use`, `install`).

**Comment by marc0der** [comment]
To be honest, I wouldn't burn too much time on testing this. Happy to merge it as it is if it works.

**Comment by helpermethod** [comment]
Hi @marc0der,

squashed the commits, skipping tests for now. I'm already using the completion for `install` for quite some time, and it's working fine (at least on my machine 😄).

**Review by marc0der — APPROVED** [review]

**Comment by marc0der** [comment]
I think this might need a quick rebase against master...

**Pull request merged**
