### PR TITLE
Fix update warn on new shells for update cmd

### PR DESCRIPTION
**Pull request by felipecrs**
Fixes https://github.com/sdkman/sdkman-cli/issues/681.

### CODE REVIEW

**Comment by felipecrs** [comment]
I tested locally and it indeed fixes the issue. How to reproduce the issue:

https://github.com/sdkman/sdkman-cli/issues/681#issuecomment-802210852

**Comment by marc0der** [comment]
Hi @felipecrs, happy to merge this but could you please explain exactly what the effect of your change is? It wasn't very apparent from the linked comment.

Also, if at all possible, it would be great to have a test that validates this fix. I realise that this is probably not feasible.

**Comment by felipecrs** [comment]
Well, in short, `sdk update` command was warning about a new version of `sdkman` available on its execution while there was none.

This issue happened because the `update` command was the only one which was not calling the `___sdman_check_version_cache` (therefore the remote version was not being defined and it caused the sdk update check to misbehave), and I could not find any reason why it was filtered just for this command.

I'll think about how feasible it is to create a test for it.

**Comment by felipecrs** [comment]
Hey @marc0der, it will be a bit complex to create a test case for this because:

1. It would require spawning clean shells
2. Rewrite the `~/.sdkman/vars/` files
3. Depend on an external server to know the latest remote version
4. Make sure the current local version is the same of the dynamic remote version
5. Or, for a negative test, make sure it's not the same as the remote version which would trigger an update

It should be possible somehow, but I don't think it actually worth it. The good news is that no tests were broken.

**Review by marc0der — APPROVED** [review]

**Comment by marc0der** [comment]
Thanks for contributing!

**Pull request merged**
