### PR TITLE
PR 1: Testing platform bug fixes

### PR DESCRIPTION
**Pull request by rgoldberg**
Multiple tests were failing on macOS because of bugs in tests related to the current platform.

Please see each commit message for the issue that was fixed by that commit.

- [X] a conversation was held in the appropriate [SDKMAN Slack](https://slack.sdkman.io) channel.
- [ ] a Github Issue was opened for this feature / bug.
- [ ] test coverage was added (Cucumber or Spock as appropriate).

### CODE REVIEW

**Comment by marc0der** [comment]
Amongst a lot of formatting (not related to fixing anything) I'm not seeing any bug fixes. How about expressing what it is you are fixing and raising a PR for only what you intended. Commit messages are also incorrect.

**Comment by rgoldberg** [comment]
Can you let me know what is wrong with the commit messages?

Also, could you not close PRs until I've had a chance to fix them to your liking?

**Comment by rgoldberg** [comment]
Each commit message is multiple lines long.  I just had "Testing:" in the first line of each to indicate that it was for testing.

The subsequent lines indicate the changes included in each commit.

e.g., the first commit "added missing mapping from 'Mac OS X' to 'Darwin'" in UnixUtils.asSdkmanPlatform(def), which fixed a macOS testing bug.

The first commit included additional cleanup (like collapsing multiple switch cases that all had the same result into one) as the file was small, and it seemed to make sense to make it more legible.

The second commit standardized a common variable name.  Not using that variable in one step caused a testing bug.  The more consistent things are, the easier it is to notice bugs & avoid / fix them, so I included that standardization with the bug fix.

**Comment by marc0der** [comment]
Please feel free to open a new PR that fixes only the naming bug.

**Comment by rgoldberg** [comment]
I fixed three bugs that caused tests to fail on macOS, one each per commit (with a little cleanup added to each commit).

I'm not sure what you mean by "PR that fixes only the naming bug".  Are you talking about the mapping from 'Mac OS X' to 'Darwin'?

The other two bugs also must be fixed, otherwise some tests will still fail on macOS, and possibly on other non-Linux64 platforms.

Will you accept one PR with all bug three fixes, accept three PRs with one bug fix each, or not accept some of the bug fixes?

If you won't accept some of the bug fixes, can you let me know why?  (I'm only referring to the bug fix parts, not the cleanup parts)

**Comment by marc0der** [comment]
To be more clear, let's have one bug fix per PR. That's how it usually works. State your intent clearly for each PR. No formatting or other noise.

**Comment by rgoldberg** [comment]
I can do that, but I will want to do all the PRs sequentially.  I don't want to create 20-some separate branches.  If you ever have an issue with a PR, please let me know without closing the PR, and I can update it to your liking.  All changes will propagate to subsequent sequential PRs.  This will save tons of time & effort.

Would you accept the aforementioned variable rename, and removing an unused, in separate PRs?  The goal is to make it simpler for others to understand the code when they read it in the future, and for standardization to help prevent future bugs.

If not, then I won't submit such changes. It's just that I don't currently know if your objection is to the changes themselves, or to those changes being included in same PR as other changes.

**Comment by marc0der** [comment]
We can bundle the bug fixes into a single PR, one fix per commit, decent commit messages, no code reformatting. If you do this, I'll happily accept.

**Pull request closed without merging**
