### PR TITLE
Add zsh completion.

### PR DESCRIPTION
**Pull request by marc0der**
Adds zsh completion under the `completion` command. This is based on the original completion script contributed to oh-my-zsh by @rgoldberg

### CODE REVIEW

**Review by helpermethod — DISMISSED** [review]
LGTM!

**Comment by helpermethod** [comment]
Looks good, though some expansions give me Perl vibes 😄 !

**Comment by marc0der** [comment]
I thought the same! It seems to work fine thought.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Review by helpermethod — APPROVED** [review]
LGTM!

**Pull request merged**
